{
 "title": "ElasticSearch",
 "description": "DIsplay ElasticSearch key metrics from Prometheus",
 "tags": [
  "prometheus",
  "elasticsearch"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "15s, 30s, 1m, 5m, 1h, 6h, 1d" },
   {
    "name": "node",
    "label": "Node name",
    "query": "label_values(elasticsearch_process_cpu_percent,name)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_status)"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "(elasticsearch_cluster_health_status == 1) +1",
     "legendFormat": "GREEN"
    },
    {
     "expr": "elasticsearch_cluster_health_status == 0",
     "legendFormat": "YELLOW"
    },
    {
     "expr": "(elasticsearch_cluster_health_status == 2) - 1",
     "legendFormat": "RED"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_number_of_nodes)"
    }
   ]
  },
  {
   "title": "Data nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_number_of_data_nodes)"
    }
   ]
  },
  {
   "title": "Pending tasks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_number_of_pending_tasks)"
    }
   ]
  },
  { "title": "Shards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Active shards",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "repeat": "shard_type",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_active_shards)"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent", "label": "CPU usage" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_process_cpu_percent{name=~\"$node\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory usage (Heap)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_jvm_memory_used_bytes{name=~\"$node\",area=\"heap\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "percentunit", "label": "Disk" }
   ],
   "targets": [
    {
     "expr": "1 - elasticsearch_filesystem_data_available_bytes{name=~\"$node\"} / elasticsearch_filesystem_data_size_bytes{name=~\"$node\"}",
     "legendFormat": "{{name}} - {{path}}"
    }
   ]
  },
  { "title": "Documents and Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Documents indexing rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Documents/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_indexing_index_total{name=~\"$node\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Indexing latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_indexing_index_time_seconds_total{name=~\"$node\"}[$interval]) / rate(elasticsearch_indices_indexing_index_total{name=~\"$node\"}[$interval]) ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Search rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Searches/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_search_query_total{name=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Search latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "rate(es_indices_search_query_time_seconds{name=~\"$node\"}[$interval]) / rate(elasticsearch_indices_search_query_total{name=~\"$node\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Documents count (with replicas)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "Documents" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_docs{name=~\"$node\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Documents deleting rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "Documents/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_docs_deleted{name=~\"$node\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Documents merging rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "Merges/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_merges_docs_total{name=~\"$node\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Caches", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Field data memory size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "es_indices_fielddata_memory_size_bytes{cluster=\"$cluster\", node=~\"$node\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Field data evictions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "Evictions/s" }
   ],
   "targets": [
    {
     "expr": "rate(es_indices_fielddata_evictions_count{cluster=\"$cluster\", node=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Query cache size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "bytes", "label": "Size" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_query_cache_memory_size_bytes{name=~\"$node\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Query cache evictions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 51 },
   "yaxes": [
    { "format": "short", "label": "Evictions/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_query_cache_evictions{name=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Query cache hits",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short", "label": "Hits/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_request_cache_memory_size_bytes{name=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Query cache misses",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 51 },
   "yaxes": [
    { "format": "short", "label": "Misses/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_get_missing_total{name=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Throttling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Indexing throttling",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_store_throttle_time_seconds_total{name=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Merging throttling",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "rate(es_indices_merges_total_throttled_time_seconds{cluster=\"$cluster\", node=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Heap used",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "bytes", "label": "Heap" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_jvm_memory_used_bytes{name=~\"$node\"}",
     "legendFormat": "{{name}} ( {{area}} )"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 73 },
   "yaxes": [
    { "format": "short", "label": "GC/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_jvm_gc_collection_seconds_count{name=~\"$node\"}[$interval])",
     "legendFormat": "{{name}} ( {{gc}} )"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 73 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_jvm_gc_collection_seconds_sum{name=~\"$node\"}[$interval])",
     "legendFormat": "{{name}} ( {{gc}} )"
    }
   ]
  }
 ]
}