{
 "title": "My Apps",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "Application name",
    "query": "label_values(process_cpu_usage,pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "My Apps JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_buffer_memory_used_bytes{pod=~\"$app\",id=\"direct\"})",
     "legendFormat": "{{pod}} ({{instance}}) tag= $tag  {{tag}}"
    }
   ]
  },
  {
   "title": "My Apps CPU  Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(process_cpu_usage{pod=~\"$app\"})",
     "legendFormat": "{{pod}} ({{instance}})"
    }
   ]
  },
  {
   "title": "My Apps Web",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(MKWEB_exec_time_seconds_max{pod=~\"$app\"})",
     "legendFormat": "{{pod}} ({{instance}}) tag= $tag  {{tag}}"
    }
   ]
  }
 ]
}