apiVersion: v1
kind: Service
metadata:
  name: es-exporter
  namespace: default
  labels:
    app: es-exporter
spec:
  ports:
  - port: 9108
    protocol: TCP
  selector:
    app: es-exporter
  type: NodePort
---          
apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: es-exporter  
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: es-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/scheme: "http"
        #prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "9108"        
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      restartPolicy: Always        
      containers:
      - name: es-exporter
        image: justwatch/elasticsearch_exporter:1.0.1      
        command:
        - /bin/elasticsearch_exporter
        - -es.uri=http://es:9200
        - -es.all=true
        securityContext:
          capabilities:
            drop:
            - SETPCAP
            - MKNOD
            - AUDIT_WRITE
            - CHOWN
            - NET_RAW
            - DAC_OVERRIDE
            - FOWNER
            - FSETID
            - KILL
            - SETGID
            - SETUID
            - NET_BIND_SERVICE
            - SYS_CHROOT
            - SETFCAP
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /health
            port: 9108
          initialDelaySeconds: 30
          timeoutSeconds: 10
        ports:
        - containerPort: 9108
        readinessProbe:
          httpGet:
            path: /health
            port: 9108
          initialDelaySeconds: 10
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 25m
            memory: 64Mi
