---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
        id: "1"
    spec:
      containers:
      - name: kafka
        image: spotify/kafka
        ports:
        - containerPort: 9092
        - containerPort: 2181
        env:
        - name: ADVERTISED_PORT
          value: "9092"
        - name: ADVERTISED_HOST
          value: kafka-service
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    name: kafka
spec:
  type: NodePort
  ports:
  - port: 9092
    nodePort: 31092  
    name: kafka-port
    protocol: TCP
  - port: 2181
    nodePort: 31181  
    name: zookeeper-port
    protocol: TCP
  selector:
    app: kafka
    id: "1"