apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: faasgateway-ingress
  namespace: openfaas
spec:
  rules:
  - host: faasgateway
    http:
      paths:
      - path: /
        backend:
          serviceName: gateway
          servicePort: 8080
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: openfaas-hello-java8func
  namespace: openfaas
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: hello-java8func
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metricName: "gateway_service_count"
      targetAverageValue: 1
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: openfaas-gateway
  namespace: openfaas
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: gateway
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metricName: "gateway_service_count"
      targetAverageValue: 1
