# -*- mode: ruby -*-
# vi: set ft=ruby :



Vagrant.require_version ">= 1.6.0"


$initscript = <<SCRIPT
     
		IP=$1
		SCRIPT=$2
	
		echo $IP
		echo $SCRIPT
	
		
		cp /vagrant/scripts/$SCRIPT $SCRIPT
		
		
		#win2linux
		sed -i -e 's/\r//g' ~/$SCRIPT
		
		chmod u+x ~/$SCRIPT
		~/$SCRIPT $IP
	
	


SCRIPT

boxes = [
    {
        :name => "hdp1",
        :interface => "enp3s0",
        :mac=> "5CA1AB1E0001",
        :ip => "192.168.10.10",
        :mem => "8192",
        :cpu => "1",
        :initscript => "master.sh"
    },
    {
        :name => "hdp2",
        :interface => "enp3s0",
        :mac=> "5CA1AB1E0002",
        :ip => "192.168.10.11",
        :mem => "8192",
        :cpu => "1",
        :initscript => "node.sh"
        
    },
    {
        :name => "hdp3",
        :interface => "enp3s0",
        :mac=> "5CA1AB1E0003",
        :ip => "192.168.10.12",
        :mem => "8192",
        :cpu => "1",
        :initscript => "node.sh"
        
    },
    {
        :name => "hdp4",
        :interface => "enp3s0",
        :mac=> "5CA1AB1E0004",
        :ip => "192.168.10.13",
        :mem => "8192",
        :cpu => "1",
        :initscript => "node.sh"
        
    }
]

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/xenial64"
#  config.vm.box = "ubuntu/trusty64"
#  config.vm.box = "bento/ubuntu-16.04"
  
  #config.vm.box_version = "20171212.0.0"

  boxes.each do |opts|
      config.vm.define opts[:name] do |config|
        config.vm.hostname = opts[:name]
        #config.vm.network :forwarded_port, host: 2222, guest: 22
        #config.ssh.username = "ubuntu"
        #config.ssh.password = "379a8188cba8c5e64b9a429f"
        
        config.vm.provider "virtualbox" do |v|
          v.customize ["modifyvm", :id, "--memory", opts[:mem]]
          v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]
          v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
          v.name = opts[:name]
        end

        config.vm.network "public_network", bridge: opts[:interface], type: "dhcp" , mac: opts[:mac]        
        #config.vm.network "public_network", bridge: opts[:interface] , mac: opts[:mac], ip: opts[:ip]
        #config.vm.network "private_network" ,  bridge: opts[:interface], ip: opts[:ip]
        
      end
  end






  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.provision "shell" do |s|
        s.privileged = false
        s.inline = $initscript
        s.args = [opts[:ip] , opts[:initscript]]
      end


 # default router
  config.vm.provision "shell",
    run: "always",
    inline: "sudo route add default gw 192.168.1.1"

  # default router ipv6
  config.vm.provision "shell",
    run: "always",
    inline: "#sudo route -A inet6 add default gw fe80::5ea1:abff:fe1e:1 dev enp0s8"

  # delete default gw on enp0s3 
  config.vm.provision "shell",
    run: "always",
    inline: "sudo route del default gw 10.0.2.2"



    end
  end



end
