# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "centos/7"

  machines = {
    'node1.example.dd'    => { :ip => '10.1.0.10'},
  #  'node2.example.dd'    => { :ip =>'10.1.0.12'},
  }

  config.ssh.pty = true

  machines.each do | hostname, attrs|
    config.vm.define hostname do |machine|
      machine.vm.hostname = hostname
      machine.vm.network :private_network, :ip => attrs[:ip]

      machine.vm.provider "virtualbox" do | v |
        v.memory = "4096"
        v.cpus = "2"
      end

    end
  end
end