# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|


$initscript = <<SCRIPT
      echo initscript. I am provisioning...
      
      echo $USER
      
sudo sed -i -r '/node1/ s/^(.*)$/#\1/g' /etc/hosts

sudo sh -c "echo '10.1.0.10      node1.example.dd' >> /etc/hosts"

sudo systemctl disable firewalld
sudo systemctl stop firewalld
sudo systemctl disable NetworkManager
sudo systemctl stop NetworkManager
sudo systemctl enable network
sudo systemctl start network


#sudo yum install -y centos-release-openstack-pike


sudo yum install -y centos-release-openstack-newton

sudo yum update -y


sudo yum install -y openstack-packstack

#sudo packstack --answer-file=/vagrant/anwserfile.txt
#sudo packstack --allinone
#packstack --allinone --provision-demo=n --os-neutron-ovs-bridge-mappings=extnet:br-ex --os-neutron-ovs-bridge-interfaces=br-ex:eth1 --os-neutron-ml2-type-drivers=vxlan,flat

	

SCRIPT





  config.vm.box = "centos/7"

  machines = {
    'node1.example.dd'    => { :ip => '10.1.0.10'},
  #  'node2.example.dd'    => { :ip =>'10.1.0.12'},
  }

  config.ssh.pty = true
  
 


  machines.each do | hostname, attrs|
    config.vm.define hostname do |machine|
      machine.vm.hostname = hostname
      machine.vm.network :private_network, :ip => attrs[:ip], :bridge => "enp3s0"
      machine.vm.network "public_network", auto_config: false
      machine.vm.network "forwarded_port", guest: 80, host: 9090
      

      machine.vm.provider "virtualbox" do | v |
        v.memory = "4096"
        v.cpus = "2"
        v.name = hostname
      end

    end
  end
  
  
  
  
  
     config.vm.define 'node1.example.dd' do |config|
      config.vm.provision "shell" do |s|
        #s.privileged = false
        s.inline = $initscript
      end
  end
  
  
  
  
  
  
  
  
  
end