apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: custom-metrics-apiserver
  name: custom-metrics-apiserver
  namespace: custom-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-metrics-apiserver
  template:
    metadata:
      labels:
        app: custom-metrics-apiserver
      name: custom-metrics-apiserver
    spec:
      serviceAccountName: custom-metrics-apiserver
      containers:
      - name: custom-metrics-apiserver
        image: directxman12/k8s-prometheus-adapter-amd64
        args:
        - --secure-port=6443
        - --tls-cert-file=/var/run/serving-cert/prometheusadapter.crt
        - --tls-private-key-file=/var/run/serving-cert/prometheusadapter.key
        - --logtostderr=true
        - --prometheus-url=http://prometheus-cs.default.svc:9090/
        - --metrics-relist-interval=1m
        - --v=10
        - --config=/etc/adapter/config.yaml
        ports:
        - containerPort: 6443
        volumeMounts:
        - name: volume-key
          mountPath: /var/run/serving-cert/prometheusadapter.key
          subPath: prometheusadapter.key
          readOnly: true
        - name: volume-crt
          mountPath: /var/run/serving-cert/prometheusadapter.crt
          subPath: prometheusadapter.crt
          readOnly: true
        - mountPath: /etc/adapter/
          name: config
          readOnly: true
        - mountPath: /tmp
          name: tmp-vol
      volumes:
      - name: config
        configMap:
          name: adapter-config
      - name: tmp-vol
        emptyDir: {}
      - name: volume-key
        #secret:
        #  secretName: key
        configMap:
          name: key
      - name: volume-crt
        configMap:
          name: crt
        