#echo "" >a.yaml && nano a.yaml && kubectl apply -f a.yaml
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: airflow-postgresql
  namespace: airflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: manual
  volumeName: airflow-postgres-pv   
