apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ambassador-ingress
  annotations:
    ingress.kubernetes.io/enable-cors: "true"
    ingress.kubernetes.io/rewrite-target: /  
spec:
  rules:
  - host: ambassador
    http:
      paths:
      - path: /
        backend:
          serviceName: my-release-ambassador-admin
          servicePort: 8877
