apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        ports:
        - name: grafana-port
          containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin"
        # removed because of tcp problem
        #- name: GF_INSTALL_PLUGINS
        #  value: "marcuscalidus-svg-panel"
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 30333
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: grafana
---
# An Ingress with 2 hosts and 3 endpoints
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-ingress
spec:
  rules:
  - host: grafana
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: 3000
