apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: httpbin-ext
spec:
  hosts:
  - httpbin.org
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: api.rubygems.org
spec:
  hosts:
  - api.rubygems.org
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api.rubygems.org
spec:
  hosts:
  - api.rubygems.org
  tls:
  - match:
    - port: 443
      sni_hosts:
      - api.rubygems.org
    route:
    - destination:
        host: api.rubygems.org
        port:
          number: 443
      weight: 100