---
apiVersion: io.jaegertracing/v1alpha1
kind: Jaeger
metadata:
  name: simplest
spec:
  strategy: allInOne
  allInOne:
    image: jaegertracing/all-in-one:1.8
    options:
      log-level: debug
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://es:9200
    #secretName: jaeger-secrets
  sampling:
    options:
      default_strategy:
        type: probabilistic
        param: 1
---
apiVersion: v1
kind: Service
metadata:
  name: zipkinjaeger
  labels:
    app: jaeger
spec:
  type: NodePort
  ports:
  - port: 9411
    #nodePort: 32017
    targetPort: 9411
    name: client
  selector:
    app: jaeger
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jaeger-ingress
  namespace: default
spec:
  rules:
  - host: jaeger
    http:
      paths:
      - path: /
        backend:
          serviceName: simplest-query
          servicePort: 16686
---
# An Ingress with 2 hosts and 3 endpoints
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: zipkin-ingress
spec:
  rules:
  - host: zipkinjaeger
    http:
      paths:
      - path: /
        backend:
          serviceName: zipkinjaeger
          servicePort: 9411
