---
apiVersion: io.jaegertracing/v1alpha1
kind: Jaeger
metadata:
  name: simplest
spec:
  strategy: allInOne
  allInOne:
    image: jaegertracing/all-in-one:1.8
    options:
      log-level: debug
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://es:9200
    #secretName: jaeger-secrets

      
  sampling:
    options:
      default_strategy:
        type: probabilistic
        param: 1
---
# Source: istio/charts/tracing/templates/service.yaml
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: zipkin
    labels:
      app: jaeger
  spec:
    type: ClusterIP
    ports:
      - port: 9411
        targetPort: 9411
        protocol: TCP
        name: http
    selector:
      app: jaeger
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jaeger-ingress
  namespace: default
spec:
  rules:
  - host: jaeger
    http:
      paths:
      - path: /
        backend:
          serviceName: simplest-query
          servicePort: 16686
---
