kind: ConfigMap
metadata:
  name: kafka-server-jaas-conf-cm
  namespace: default
apiVersion: v1
data:
  kafka_server_jaas.conf: |-
    KafkaServer {
        com.sun.security.auth.module.Krb5LoginModule required
        useKeyTab=true
        storeKey=true
        keyTab="/opt/kafka/config/kafka.keytab"
        principal="kafka/{HOSTNAME_FQDN}@KAFKA.SECURE";
    };

    // ZooKeeper client authentication
    Client {
        com.sun.security.auth.module.Krb5LoginModule required
        useKeyTab=true
        storeKey=true
        keyTab="/opt/kafka/config/kafka.keytab"
        principal="kafka/{HOSTNAME_FQDN}@KAFKA.SECURE";
    };    
---
kind: ConfigMap
metadata:
  name: kafka-krb5-conf-cm
  namespace: default
apiVersion: v1
data:
  krb5.conf: |-
    [logging]
      default = FILE:/var/log/krb5libs.log
      kdc = FILE:/var/log/krb5kdc.log
      admin_server = FILE:/var/log/kadmind.log
    
    [libdefaults]
        default_realm = KAFKA.SECURE
        kdc_timesync = 1
        ticket_lifetime = 24h
    
    [realms]
        KAFKA.SECURE = {
          admin_server = kerberos
          kdc  = kerberos
          } 
---
apiVersion: v1
kind: Service
metadata:
  name: k-cs
  labels:
    app: kafka
spec:
  type: NodePort
  ports:
  - port: 9092
    nodePort: 30092
    targetPort: 9092
    name: client
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: k-hs
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: client
  - port: 8080
    name: jmxagent
  clusterIP: None
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: "k-hs"
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
        kubernetes.io/name: "kafka"
        tier: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/scheme: "http"
        prometheus.io/path: "/"
        prometheus.io/port: "8080"          
    spec:
      containers:
      - name: kafka
        image: marcinkasinski/kafkacluster
        #imagePullPolicy: Always        
        imagePullPolicy: Never        
        ports:
        - containerPort: 9092
          name: client
        env:
        - name: "POD_NAME"
          valueFrom:
            fieldRef:
              fieldPath: metadata.name              
        - name: "BROKER_NODES"
          value: "kafka-0.k-hs.default.svc.cluster.local:9092,kafka-1.k-hs.default.svc.cluster.local:9092,kafka-2.k-hs.default.svc.cluster.local:9092"
        - name: "JAAS_FILE_LOCATION"
          value: "/opt/kafka/config/kafka_server_jaas.conf"
        - name: "JAAS_FILE_LOCATION_RO"
          value: "/opt/kafka/config/kafka_server_jaas.conf_RO"
        # default 16kb we set to 64
        - name: "KAFKA_PARAM_BATCH_SIZE"
          value: "65536"
        - name: "KAFKA_PARAM_listeners"
          #value: "PLAINTEXT://0.0.0.0:9092,SSL://0.0.0.0:9093,SASL_SSL://0.0.0.0:9094"
          value: "PLAINTEXT://0.0.0.0:9092,SASL_PLAINTEXT://0.0.0.0:9093"
        - name: "KAFKA_PARAM_advertised_listeners"
          #value: "PLAINTEXT://{HOSTNAME_FQDN}:9092,SASL_PLAINTEXT://{HOSTNAME_FQDN}:9093"
          value: "PLAINTEXT://{HOSTNAME_FQDN}:9092,SASL_PLAINTEXT://{HOSTNAME_FQDN}:9093"
        - name: "KAFKA_PARAM_ZOOKEEPER_CONNECT"
          value: "zk-0.zk-hs.default.svc.cluster.local:2181,zk-1.zk-hs.default.svc.cluster.local:2181,zk-2.zk-hs.default.svc.cluster.local:2181/kafka"
        - name: "KAFKA_PARAM_security_inter_broker_protocol"
          value: "SASL_PLAINTEXT"
        - name: "KAFKA_PARAM_sasl_mechanism_inter_broker_protocol"
          #value: "GSSAPI"
          value: "PLAIN"
        - name: "KAFKA_PARAM_sasl_enabled_mechanisms"
          value: "GSSAPI,PLAIN"
          #value: "GSSAPI"
        - name: "KAFKA_PARAM_sasl_kerberos_service_name"
          value: "kafka"
        volumeMounts:
        - name: config-volume-krb5-conf-cm
          mountPath: /etc/krb5.conf
          subPath: krb5.conf        
        - name: config-volume-kafka-0-service-keytab
          mountPath: /opt/kafka/config/kafka-0.service.keytab
          subPath: kafka-0.service.keytab
        - name: config-volume-kafka-1-service-keytab
          mountPath: /opt/kafka/config/kafka-1.service.keytab
          subPath: kafka-1.service.keytab
        - name: config-volume-kafka-2-service-keytab
          mountPath: /opt/kafka/config/kafka-2.service.keytab
          subPath: kafka-2.service.keytab
        - name: config-volume-kafka-server-jaas-conf-cm
          mountPath: /opt/kafka/config/kafka_server_jaas.conf_RO
          subPath: kafka_server_jaas.conf
        - name: kafka-logs
          mountPath: /opt/kafka/config/kafka-logs
      volumes:
        - name: config-volume-krb5-conf-cm
          configMap:
            name: kafka-krb5-conf-cm
        - name: config-volume-kafka-0-service-keytab
          configMap:
            name: kafka-0-service-keytab
        - name: config-volume-kafka-1-service-keytab
          configMap:
            name: kafka-1-service-keytab
        - name: config-volume-kafka-2-service-keytab
          configMap:
            name: kafka-2-service-keytab
        - name: config-volume-kafka-server-jaas-conf-cm
          configMap:
            name: kafka-server-jaas-conf-cm
        - name: kafka-logs
          emptyDir: {}    