apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafkacluster
  namespace: default
  labels:
    app: kafkacluster
    version: v5.5.1
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  serviceName: kafkacluster
  replicas: 3
  selector:
    matchLabels:
      app: kafkacluster
      version: v5.5.1
  template:
    metadata:
      labels:
        app: kafkacluster
        version: v5.5.1
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: kafkacluster
      containers:
      - image: marcinkasinski/kafkacluster
        name: kafkacluster
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            cpu: 1000m
            memory: 2.5Gi
          requests:
            memory: 2.5Gi
            cpu: 100m
        ports:
        - containerPort: 9200
          name: db
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        env:
        - name: "NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: "ES_JAVA_OPTS"
          value: "-XX:-AssumeMP"
      # Elasticsearch requires vm.max_map_count to be at least 262144.
      # If your OS already sets up this number to a higher value, feel free
      # to remove this init container.
      initContainers:
      - image: alpine:3.6
        command: ["/sbin/sysctl", "-w", "vm.max_map_count=262144"]
        name: kafkacluster-init
        securityContext:
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: kafkacluster
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 9092
    protocol: TCP
    nodePort: 30092    
    targetPort: 9092
  selector:
    app: kafkacluster
