apiVersion: v1
kind: Service
metadata:
  name: k-hs
  labels:
    app: kafka
spec:
  ports:
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  clusterIP: None
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: "k-hs"
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: marcinkasinski/kafkacluster
        imagePullPolicy: Always        
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        env:
        - name: "ZOOKEEPER_CONNECT"
          value: "zk-0.zk-cs.default.svc.cluster.local:2281,zk-1.zk-cs.default.svc.cluster.local:2281,zk-2.zk-cs.default.svc.cluster.local:2281"
        - name: "BROKER_NODES"
          value: "server.1=zk-0.ks.default.svc.cluster.local:2888:3888;server.2=zk-1.ks.default.svc.cluster.local:2888:3888;server.3=zk-2.ks.default.svc.cluster.local:2888:3888"
          