apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-manager-deployment
  labels:
    app: kafka-manager  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-manager
  template:
    metadata:
      labels:
        app: kafka-manager
    spec:
      containers:
      - name: kafka-manager
        image: hlebalbau/kafka-manager:latest
        ports:
        - name: kafka-manager
          containerPort: 9000
        env:
        - name: ZK_HOSTS
          value: "zk-0.zk-hs.default.svc.cluster.local:2181,zk-1.zk-hs.default.svc.cluster.local:2181,zk-2.zk-hs.default.svc.cluster.local:2181"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-manager
spec:
  type: NodePort
  ports:
  - port: 9000
    protocol: TCP
    name: http
  selector:
    app: kafka-manager
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kafka-manager-ingress
spec:
  rules:
  - host: kafka-manager
    http:
      paths:
      - path: /
        backend:
          serviceName: kafka-manager
          servicePort: 9000
