apiVersion: v1
kind: Service
metadata:
  name: k-cs
  labels:
    app: kafka
spec:
  type: NodePort
  ports:
  - port: 9092
    nodePort: 30092
    targetPort: 9092
    name: client
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: k-hs
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: client
  - port: 8080
    name: jmxagent
  clusterIP: None
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: "k-hs"
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
        kubernetes.io/name: "kafka"
        tier: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/scheme: "http"
        prometheus.io/path: "/"
        prometheus.io/port: "8080"          
    spec:
      containers:
      - name: kafka
        image: marcinkasinski/kafkacluster
        imagePullPolicy: Always        
        ports:
        - containerPort: 9092
          name: client
        volumeMounts:
        - mountPath: /tmp/kafka-logs
          name: kafka-logs   
        env:
        - name: "ZOOKEEPER_CONNECT"
          value: "zk-0.zk-hs.default.svc.cluster.local:2181,zk-1.zk-hs.default.svc.cluster.local:2181,zk-2.zk-hs.default.svc.cluster.local:2181/kafka"
        - name: "BROKER_NODES"
          value: "1=kafka-0.k-hs.default.svc.cluster.local;2=kafka-1.k-hs.default.svc.cluster.local;3=kafka-2.k-hs.default.svc.cluster.local"
      volumes:
      - name: kafka-logs
        emptyDir: {}    