kind: ConfigMap
metadata:
  name: kafka-krb5-conf-cm
  namespace: default
apiVersion: v1
data:
  krb5.conf: |-
    [logging]
      default = FILE:/var/log/krb5libs.log
      kdc = FILE:/var/log/krb5kdc.log
      admin_server = FILE:/var/log/kadmind.log
    
    [libdefaults]
        default_realm = KAFKA.SECURE
        kdc_timesync = 1
        ticket_lifetime = 24h
    
    [realms]
        KAFKA.SECURE = {
          admin_server = kerberos
          kdc  = kerberos
          } 
---
apiVersion: v1
kind: Service
metadata:
  name: k-cs
  labels:
    app: kafka
spec:
  type: NodePort
  ports:
  - port: 9092
    nodePort: 30092
    targetPort: 9092
    name: client
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: k-hs
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: client
  - port: 8080
    name: jmxagent
  clusterIP: None
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: "k-hs"
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
        kubernetes.io/name: "kafka"
        tier: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/scheme: "http"
        prometheus.io/path: "/"
        prometheus.io/port: "8080"          
    spec:
      containers:
      - name: kafka
        image: marcinkasinski/kafkacluster
        imagePullPolicy: Always        
        ports:
        - containerPort: 9092
          name: client
        env:
        - name: "POD_NAME"
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "ZOOKEEPER_CONNECT"
          value: "zk-0.zk-hs.default.svc.cluster.local:2181,zk-1.zk-hs.default.svc.cluster.local:2181,zk-2.zk-hs.default.svc.cluster.local:2181/kafka"
        - name: "BROKER_NODES"
          value: "kafka-0.k-hs.default.svc.cluster.local:9092,kafka-1.k-hs.default.svc.cluster.local:9092,kafka-2.k-hs.default.svc.cluster.local:9092"
        # default 16kb we set to 64
        - name: "KAFKA_PARAM_BATCH_SIZE"
          value: "65536"
        volumeMounts:
        - name: config-volume-krb5-conf-cm
          mountPath: /etc/krb5.conf
          subPath: krb5.conf        
        - name: config-volume-kafka-service-keytab
          mountPath: /tmp/kafka.service.keytab
          subPath: kafka.service.keytab        
        - name: kafka-logs
          mountPath: /tmp/kafka-logs
      volumes:
        - name: config-volume-krb5-conf-cm
          configMap:
            name: kafka-krb5-conf-cm
        - name: config-volume-kafka-service-keytab
          configMap:
            name: kafka-service-keytab
        - name: kafka-logs
          emptyDir: {}    