kind: ConfigMap
metadata:
  name: kdc-conf-cm
  namespace: default
apiVersion: v1
data:
  kdc.conf: |-
    [kdcdefaults]
      kdc_ports = 88
      kdc_tcp_ports = 88
      default_realm=KAFKA.SECURE
    [realms]
      KAFKA.SECURE = {
        acl_file = /var/kerberos/krb5kdc/kadm5.acl
        dict_file = /usr/share/dict/words
        admin_keytab = /var/kerberos/krb5kdc/kadm5.keytab
        supported_enctypes = aes256-cts:normal aes128-cts:normal des3-hmac-sha1:normal arcfour-hmac:normal camellia256-cts:normal camellia128-cts:normal des-hmac-sha1:normal des-cbc-md5:normal des-cbc-crc:normal
      }           
---
kind: ConfigMap
metadata:
  name: kadm5-acl-cm
  namespace: default
apiVersion: v1
data:
  kadm5.acl: |-
    */admin@KAFKA.SECURE *
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kerberos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kerberos
  template:
    metadata:
      labels:
        app: kerberos
      annotations:
    spec:
      containers:
      - name: kerberos
        image: marcinkasinski/krb5-server
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 88
        env:
        - name: AAAAAAA
          value: "AAAAAA"
        volumeMounts:
        - name: config-volume-kdc-conf-cm
          mountPath: /etc/krb5kdc/kdc.conf
          subPath: kdc.conf
        - name: config-volume-kadm5-acl-cm
          mountPath: /etc/krb5kdc/kadm5.acl
          subPath: kadm5.acl
      volumes:
        - name: config-volume-kdc-conf-cm
          configMap:
            name: kdc-conf-cm          
        - name: config-volume-kadm5-acl-cm
          configMap:
            name: kadm5-acl-cm          
---
apiVersion: v1
kind: Service
metadata:
  name: kerberos
spec:
  type: NodePort
  ports:
  - port: 88
    targetPort: 88
    protocol: TCP
    name: krb
  selector:
    app: kerberos
---
