apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfsmysql
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: k8smaster.local
    path: "/var/nfs/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfsmysql
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql    
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - name: mysql-port
          containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "secret"
#        volumeMounts:
#        - name: nfsmysql
#          mountPath: /var/lib/mysql
#      volumes:
#      - name: nfsmysql
#        persistentVolumeClaim:
#          claimName: nfsmysql

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: NodePort
  ports:
  - port: 3306
    nodePort: 30306
    targetPort: 3306
    protocol: TCP
    name: http
  selector:
    app: mysql