kind: ConfigMap
metadata:
  name: prometheus-config-prometheus.yml
  namespace: default
apiVersion: v1
data:
  prometheus.yml: |-
    # my global config MK !!!!!!!!!!!!!!!
    global:
      scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
      evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
      # scrape_timeout is set to the global default (10s).

    # Alertmanager configuration
    alerting:
      alertmanagers:
      - static_configs:
    	- targets:
    	  # - alertmanager:9093

    # Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
    rule_files:
      # - "first_rules.yml"
      # - "second_rules.yml"

    # A scrape configuration containing exactly one endpoint to scrape:
    # Here it's Prometheus itself.
    scrape_configs:
      # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
      - job_name: 'prometheus'

    	# metrics_path defaults to '/metrics'
    	# scheme defaults to 'http'.

    	static_configs:
    	- targets: ['localhost:9090']

 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  labels:
    app: prometheus  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: quay.io/prometheus/prometheus
        args: [ "--config.file=/etc/prometheus2/prometheus.yml", "--storage.tsdb.path=/prometheus", "--web.console.libraries=/usr/share/prometheus/console_libraries", "--web.console.templates=/usr/share/prometheus/consoles" ]
        ports:
        - name: prometheus-port
          containerPort: 9090
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "secret"
        - name: MYSQL_HOST
          value: "mysql"
        - name: PMA_HOST
          value: "mysql"
        volumeMounts:
        - name: config-volume-prometheus-yml
          mountPath: /etc/prometheus2
      volumes:
        - name: config-volume-prometheus-yml
          configMap:
            # Provide the name of the ConfigMap containing the files you want
            # to add to the container
            name: prometheus-config-prometheus.yml	
          
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: NodePort
  ports:
  - port: 9090
    nodePort: 30909
    targetPort: 9090
    protocol: TCP
    name: http
  selector:
    app: prometheus
---
# An Ingress with 2 hosts and 3 endpoints
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus-ingress
spec:
  rules:
  - host: prometheus
    http:
      paths:
      - path: /
        backend:
          serviceName: prometheus
          servicePort: 9090
