apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3
        ports:
        - name: rabbitmq-port1
          containerPort: 15672
        - name: rabbitmq-port2
          containerPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: NodePort
  ports:
  - port: 15672
    nodePort: 31672
    targetPort: 15672
    protocol: TCP
    name: http
  - port: 5672
    nodePort: 30672
    targetPort: 5672
    protocol: TCP
    name: http2
  selector:
    app: rabbitmq
---
# An Ingress with 2 hosts and 3 endpoints
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rabbitmq-ingress
spec:
  rules:
  - host: rabbitmq
    http:
      paths:
      - path: /
        backend:
          serviceName: rabbitmq
          servicePort: 15672
