apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootrabbitmqlistener-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springbootrabbitmqlistener
  template:
    metadata:
      labels:
        app: springbootrabbitmqlistener
    spec:
      containers:
      - name: springbootrabbitmqlistener
        image: marcinkasinski/springbootrabbitmqlistener
        imagePullPolicy: Always
        ports:
        - name: nodejs-port
          containerPort: 9191
        env:
        - name: SPRING_PROFILE
          value: "prd"
---
apiVersion: v1
kind: Service
metadata:
  name: springbootrabbitmqlistener
spec:
  type: NodePort
  ports:
  - port: 9191
    nodePort: 30091
    targetPort: 9191
    protocol: TCP
    name: http
  selector:
    app: springbootrabbitmqlistener