apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springbootweb
  template:
    metadata:
      labels:
        app: springbootweb
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/scheme: "http"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "7070"  
    spec:
      containers:
      - name: springbootweb
        image: marcinkasinski/springbootweb
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 7070
        env:
        - name: SPRING_PROFILE
          value: "prd"          
        - name: APP_AJAX_URL
          value: "http://springbootmicroservice:30080/api/get-by-email?email=ajax@ajax.com"          
        - name: APP_REST_URL
          value: "http://springbootmicroservice-cs.default.svc.cluster.local:9191/api/adduser"
        - name: KAFKA_BROKER_NODES
          value: "kafka-0.k-hs.default.svc.cluster.local:9092,kafka-1.k-hs.default.svc.cluster.local:9092,kafka-2.k-hs.default.svc.cluster.local:9092"          
---
apiVersion: v1
kind: Service
metadata:
  name: springbootweb
spec:
  type: NodePort
  ports:
  - port: 7070
    nodePort: 30070
    targetPort: 7070
    protocol: TCP
    name: http
  selector:
    app: springbootweb
---
# An Ingress with 2 hosts and 3 endpoints
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: springbootweb-ingress
  annotations:
    ingress.kubernetes.io/enable-cors: "true"
    ingress.kubernetes.io/rewrite-target: /  
spec:
  rules:
  - host: springbootweb
    http:
      paths:
      - path: /
        backend:
          serviceName: springbootweb
          servicePort: 7070
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: springbootweb
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: springbootweb
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metricName: MKWEB_exec_time_seconds_max
      targetAverageValue: 2m
---
