apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootmicroservice-deployment
  annotations:
    pod.beta.kubernetes.io/init-containers: '[
        {
            "name": "init-myservice",
            "image": "busybox",
            "command": ["sh", "-c", "ls -l"]
        }
    ]'  
spec:
  replicas: 1
  selector:
    app: springbootmicroservice
  template:
    metadata:
      labels:
        app: springbootmicroservice
    spec:
      containers:
      - name: springbootmicroservice
        image: marcinkasinski/springbootmicroservice
        imagePullPolicy: Always
        ports:
        - name: http-port
          containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: springbootmicroservice
spec:
  type: NodePort
  ports:
  - port: 8081
    nodePort: 30081
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: springbootmicroservice
---
# An Ingress with 2 hosts and 3 endpoints
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: springbootmicroservice-ingress
  annotations:
    ingress.kubernetes.io/enable-cors: "true"
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: springbootmicroservice
    http:
      paths:
      - path: /
        backend:
          serviceName: springbootmicroservice
          servicePort: 8081
