apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: weave-ingress
  annotations:
spec:
  rules:
  - host: weave
    http:
      paths:
      - path: /
        backend:
          serviceName: weave-scope-app
          servicePort: 80
---
