apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: springbootzipkin-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: springbootzipkin
    spec:
      containers:
      - name: springbootzipkin
#        image: marcinkasinski/springbootzipkin
        image: openzipkin/zipkin        
        ports:
        - name: web-port
          containerPort: 9411
        env:
        - name: JAVA_OPTS
          value: "-Dlogging.level.zipkin=DEBUG -Dlogging.level.zipkin2=DEBUG -Dlogging.level.=DEBUG -Dlogging.level.root=DEBUG"          
          
---
apiVersion: v1
kind: Service
metadata:
  name: springbootzipkin
spec:
  type: NodePort
  ports:
  - port: 7777
    targetPort: 9411
    protocol: TCP
    name: http
  selector:
    app: springbootzipkin
---
# An Ingress with 2 hosts and 3 endpoints
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: springbootzipkin-ingress
spec:
  rules:
  - host: zipkin
    http:
      paths:
      - path: /
        backend:
          serviceName: springbootzipkin
          servicePort: 7777
