apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoonavigator-deployment
  labels:
    app: zoonavigator  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zoonavigator
  template:
    metadata:
      labels:
        app: zoonavigator
    spec:
      containers:
      - name: zoonavigator
        image: elkozmon/zoonavigator-web:latest
        ports:
        - name: zoonavigator
          containerPort: 7070
        env:
        - name: ZK_HOSTS
          value: "zk-0.zk-hs.default.svc.cluster.local:2181,zk-1.zk-hs.default.svc.cluster.local:2181,zk-2.zk-hs.default.svc.cluster.local:2181"
---
apiVersion: v1
kind: Service
metadata:
  name: zoonavigator
spec:
  type: NodePort
  ports:
  - port: 7070
    protocol: TCP
    name: http
  selector:
    app: zoonavigator
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: zoonavigator-ingress
spec:
  rules:
  - host: zoonavigator
    http:
      paths:
      - path: /
        backend:
          serviceName: zoonavigator
          servicePort: 7070
