---
- hosts: all
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
      become: yes
    - name: start nginx
      service:
          name: nginx
          state: started
      become: yes
    - name: copy the nginx config file and restart nginx
      copy:
        src: /vagrant/conf/nginx/static_site.cfg
        dest: /etc/nginx/sites-available/static_site.cfg
      become: yes
    - name: create symlink
      file:
        src: /etc/nginx/sites-available/static_site.cfg
        dest: /etc/nginx/sites-enabled/default
        state: link
      become: yes
    - name: create directory
      file:
        path: /home/vagrant/wwwcontent
        state: directory
        owner: www-data
        group: www-data
        mode: 0775
        recurse: yes      
    - name: copy the content of the web site
      copy:
        src: /vagrant/conf/nginx/index.html
        dest: /home/vagrant/wwwcontent/index.html
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes
    - name: Run custom script
      script: /vagrant/scripts/script.sh --some-argument 1234
      register: out
    - debug: var=out.stdout_lines      
      