apiVersion: v1
kind: Service
metadata:
  name: mongodb-configdb-hs
  namespace: default
  labels:
    name: mongodb-configdb
spec:
  ports:
  - port: 27019
    targetPort: 27019
  clusterIP: None
  selector:
    role: mongodb-configdb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-configdb
  namespace: default
  labels:
    app: mongodb-configdb
spec:
  selector:
    matchLabels:
      role: mongodb-configdb # has to match .spec.template.metadata.labels
  serviceName: mongodb-configdb-hs
  replicas: 1
  template:
    metadata:
      labels:
        role: mongodb-configdb
        tier: configdb
        replicaset: configdb
        
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/scheme: "http"
        #prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "9216"
        
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: replicaset
                  operator: In
                  values:
                  - configdb
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongodbcfg-prometheus-exporter
#          image: eses/mongodb_exporter
          image: ssheehy/mongodb-exporter
          ports:
          - name: mongodbexporter
            containerPort: 9104
          env:
          - name: MONGODB_URI
            value: "mongodb://localhost:27019"
#          - name: HTTP_AUTH
#            value: "user:password"
      
        - name: mongodb-configdb-container
          image: mongo
          command:
            - "mongod"
            - "--port"
            - "27019"
            - "--dbpath"
            - "/mongo-disk"
            - "--bind_ip"
            - "0.0.0.0"
            - "--replSet"
            - "MyConfigRepl" 
            - "--configsvr"
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
          ports:
            - containerPort: 27019
          volumeMounts:
            - name: mongodb-data
              mountPath: /mongo-disk
      volumes:
      - name: mongodb-data
        emptyDir: {}