---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootmicroservice-v2
  labels:
    app: springbootmicroservice  
spec:
#  serviceName: "springbootmicroservice-hs"
  replicas: 1
#  updateStrategy:
#    type: RollingUpdate
#  podManagementPolicy: Parallel  
  selector:
    matchLabels:
      app: springbootmicroservice    
  template:
    metadata:
      labels:
        app: springbootmicroservice
        version: v2
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/scheme: "http"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "9191"        
    spec:
      initContainers:
      #- name: init-springbootmicroservice-monitoring
       # image: openjdk:9
        #command: ['sh', '-c', 'apt update && apt install -y netcat && echo "Waiting monitoring to launch"  && while ! nc -z monitoring-influxdb.kube-system.svc.cluster.local 8086; do   echo "waiting..." ; sleep 5 ; done ;  curl -POST http://monitoring-influxdb.kube-system.svc.cluster.local:8086/query --data-urlencode "q=CREATE DATABASE metrics"']
      containers:
      - name: springbootmicroservice
        image: marcinkasinski/springbootmicroservice
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /actuator/prometheus
            port: 9191
            httpHeaders:
            - name: X-Custom-Header
              value: Awesome
          initialDelaySeconds: 300
          periodSeconds: 10
        ports:
        - name: http
          containerPort: 9191
        env:
        - name: VERSION_NAME
          value: "V2"
        - name: SPRING_PROFILE
          value: "prd"
        - name: "EXTRA_JAVA_ARGS"
          value: "-Dspring.cloud.bootstrap.location=adad"
        - name: MONGODB_URL
          value: "mongodb://mongodb-router-cs.default.svc.cluster.local:27017/mkdatabase"
        - name: KAFKA_BROKER_NODES
          value: "kafka-0.k-hs.default.svc.cluster.local:9092,kafka-1.k-hs.default.svc.cluster.local:9092,kafka-2.k-hs.default.svc.cluster.local:9092"
        volumeMounts:
        - name: config-springbootmicroservice-bootstrap-yml-cm
          mountPath: /usr/src/myapp/config/bootstrap.yml
          subPath: bootstrap.yml
      volumes:
        - name: config-springbootmicroservice-bootstrap-yml-cm
          configMap:
            name: springbootmicroservice-bootstrap-yml-cm
---
 