---
- name: Configure Nexpose Console
  hosts: nexpose-consoles
  become: yes

  vars:
    nexpose_engine: False
    nexpose_console_port: 443
    nexpose_logon_password: "admin"
#  vars_prompt:
#    - name: nexpose_logon_password
#      prompt: "Enter logon password"
#      private: yes
#      confirm: yes
  roles:
    - nexpose
