---
- name: Configure Nexpose Engine
  hosts: nexpose-engines
  become: yes
  vars:
    nexpose_logon_password: "admin"
#  vars_prompt:
#    - name: nexpose_logon_password
#      prompt: "Enter logon password"
#      private: yes
#      confirm: yes
  roles:
    - nexpose